### ISSUE TITLE
无法实现微信推送

### ISSUE THREAD

**Issue by alexlife** [HLNN/LOF#3]
您好，我完成了以下操作并调低溢价通知阈值但多次测试均无法得到微信推送，不知道问题在哪，还请协助，感谢！
1.参考readme一步一步完成了配置，也在Server酱上申请了秘钥并绑定在【Settings】->【Secrets】
2.在Server酱中绑定微信，并通过Server酱“在线发送工具”发送消息到微信成功
3.修改通知阈值、通知时间，发现到预定通知时间后 All workflows 中会有一条Scheduled的记录，但微信端无消息提醒

也删除过项目重新fork并按照以上几步配置，依然无微信通知

**Comment by HLNN** [comment]
我把你的代码拉到本地测试过了，代码没有问题。
你可以再检查一下密钥的配置：
 - 申请的密钥可用，且绑定成功
 - 在【Settings】->【Secrets】中，以`SERVERCHANKEY : API_KEY`的形式设置正确

**Comment by HLNN** [comment]
Issues我先关了，有问题可以再Reopen

**Comment by alexlife** [comment]
搞定了，是Secret的name写错了，多谢
